import { StyleSheet } from "react-native";

export const headercategoria = StyleSheet.create({
  fullview: {
    flex: 0,
  },
  header: {
    flexDirection: "row",
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 50,
  },
  logo: {
    width: 90,
    height: 90,
    marginLeft: "auto",
    marginRight: "auto",
    resizeMode: "contain",
  },
  viewprincipal: {
    flex: 2,
  },
  banner: {
    marginTop: 20,
    height: "25%",
    width: "100%",
  },
  imgbanner: {
    height: "100%",
    width: "95%",
    resizeMode: "contain",
    borderRadius: 20,
    alignSelf: "center",
  },
  viewprodutos: {
    marginTop: 10,
    backgroundColor: "red",
  },
  produtos: {
    borderBottomColor: "black",
    borderWidth: 0,
    borderRadius: 10,
    width: 181,
    height: 250,
    marginLeft: 25,
    marginRight: 25,
    marginTop: 40,
  },
  imageprod: {
    borderWidth: 2,
    height: "100%",
    width: "100%",
    borderRadius: 20,
  },
  txtprod: {
    position: "absolute",
    fontSize: 25,
    color: "black",
    marginTop: 200,
    marginLeft: 55,
    borderRadius: 5,
    backgroundColor: "white",
    width: 120,
    textAlign: "center",
  },
  txtprod1: {
    position: "absolute",
    fontSize: 25,
    color: "white",
    marginTop: 110,
    width: 181,
    textAlign: "center",
    borderColor: "black",
    borderRadius: 10,
    backgroundColor: "black",
    opacity: 0.5,
  },
  scrollview: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: -30,
  },
  viewfind: {
    paddingTop: 0,
  },
  search: {
    width: 34,
    height: 34,
    left: 40,
    top: 45,
  },
  input: {
    borderColor: "#0c0031",
    borderRadius: 28,
    borderWidth: 2,
    width: "90%",
    height: 55,
    marginRight: "auto",
    marginLeft: "auto",
    paddingLeft: 65,
    fontWeight: "bold",
    fontSize: 22,
  },
});
