import { StyleSheet } from "react-native";

export const detalhes = StyleSheet.create({
  teladetalhes: {
    backgroundColor: "#efefff",
    flex: 3,
  },
  nomeroupa: {
    fontSize: 40,
    marginLeft: 35,
  },
  descricao: {
    fontSize: 25,
    marginTop: 5,
    color: "black",
    marginLeft: 35,
  },
  categoria: {
    alignSelf: "center",
    fontSize: 20,
    marginTop: 10,
    color: "black",
  },
  viewquantidade: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  txtquantidade: {
    fontSize: 25,
  },
  quantidade: {
    backgroundColor: "silver",
    borderRadius: 20,
    width: 50,
    height: 50,
    alignSelf: "center",
    left: 20,
    fontSize: 25,
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 20,
  },
  tamanho: {
    fontSize: 25,
    fontWeight: "bold",
    marginLeft: 35,
    backgroundColor: "silver",
    borderRadius: 10,
    width: "10%",
    textAlign: "center",
    marginTop: 10,
  },
  precoroupa: {
    fontSize: 43,
    fontWeight: "bold",
    color: "black",
    textAlign: "center",
    alignSelf: "center",
    backgroundColor: "silver",
    width: "50%",
    borderRadius: 15,
  },
  roupa: {
    resizeMode: "contain",
    width: 400,
    height: 400,
    borderRadius: 20,
    marginLeft: 30,
    marginRight: 30,
  },
  btnadicionar: {
    width: 250,
    height: 50,
    marginTop: 20,
    marginRight: "auto",
    marginLeft: "auto",
    backgroundColor: "#1d0940",
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  txtadicionar: {
    color: "white",
    fontSize: 25,
  },
  scrollview: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginVertical: 40,
  },
});
